// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rnV-Sg2t6FCQe_9cKDdtkI5X5Uy57hk',
    appId: '1:933921576315:web:8964a985c414cef05399de',
    messagingSenderId: '933921576315',
    projectId: 'pachakutech-website-blogs',
    authDomain: 'pachakutech-website-blogs.firebaseapp.com',
    storageBucket: 'pachakutech-website-blogs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM2uNY9rgOhlrdqNdqrrMB35D15shTaaQ',
    appId: '1:933921576315:android:4ad0148008e1b27b5399de',
    messagingSenderId: '933921576315',
    projectId: 'pachakutech-website-blogs',
    storageBucket: 'pachakutech-website-blogs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxKhZWFIjsHEaAL23L_2QuOsvXLhoA9-c',
    appId: '1:933921576315:ios:de32a62d20bebdd15399de',
    messagingSenderId: '933921576315',
    projectId: 'pachakutech-website-blogs',
    storageBucket: 'pachakutech-website-blogs.firebasestorage.app',
    iosBundleId: 'com.pachakutech.pachakutechWebsite',
  );

}